# -*- coding: utf-8 -*-
"""Cognizance Task-3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BIiHPRTSHwWRNev7g27Ub_gcFiexNUmh
"""


Question-1:

import numpy as np
x = int(input("First number :"))  
y = int(input("Last number : "))  
arr=[]
for i in range(x,y+1):
    arr.append(i)
z = 5
arr1 = np.zeros(len(arr) + (len(arr)-1)*(z))
for a in range(len(arr)):
    arr1[::z+1] = arr
print(arr1)


Question-2:

import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
array_equal = np.allclose(x, y)
print(array_equal)


Question-3:

import numpy as np
print(0 * np.nan)
print(np.nan != np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)


Question-4:

import pandas as pd
ser = pd.Series(['amrita', 'school', 'of', 'engineering', 'chennai' , 'campus'])
Series = ser.map(lambda x: x[0].upper() + x[1:-1] + x[-1].lower())
print(' '.join(Series))


Question-5(i):

import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([11, 12, 13, 14])
arr3 = np.add(arr1,arr2)
print("arr1:", arr1)
print("arr2:", arr2)
print("arr1+arr2:", arr3)


Question-5(ii):

import numpy as np
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[1,0,1], [1,1,0], [0,1,1]])
print("Matrix A is:\n",A)
print("Matrix B is:\n",B)
C = np.matmul(A,B)
print("Matrix multiplication of matrix A and B is:\n",C)

